### ISSUE TITLE
Multi Polygon issue

### ISSUE THREAD

**Issue by borut-t** [GEOSwift/GEOSwift#142] opened 2019-03-18 10:43 UTC
This issue is related to the already opened [PR](https://github.com/GEOSwift/GEOSwift/pull/92).

The thing is that geosjon can return multiple polygons nested inside one `Polygon` object. Here is an example:
```json
{
  "type":"FeatureCollection",
  "features":[
    {
      "type":"Feature",
      "geometry":{
        "type":"GeometryCollection",
        "geometries":[
          {
            "type":"Polygon",
            "coordinates":[
              [...],
              [...],
              [...],
              [...]
            ]
          },
          {
            "type":"Polygon",
            "coordinates":[
              [...],
              [...]
            ]
          }
        ]
      }
    }
  ]
}
```

I've temporary fixed that in a way to check if `coordinates` array contains multiple subarrays, then I change type from `Polygon` to `MutliPolygon`
```swift
if geomCoordinates.count > 1 {
  geomType = "MultiPolygon"
}
```

**Comment by macdrevx** [comment] 2019-03-31 17:20
Thanks @borut-t. I’m going to close this as a duplicate of #90. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by macdrevx** 2019-03-31 17:20 UTC
