### ISSUE TITLE
Build failure on Xcode 10 after cocoa pods update

### ISSUE THREAD

**Issue by joeuelk** [GEOSwift/GEOSwift#122] opened 2018-10-12 17:17 UTC
I had this working under Xcode 10 by changing the build settings but after recently updating cocoa pods (and homebrew although I'm not sure if this is related) I'm now getting a "geos/platform.h file not found" error. 

I'm also seeing errors under GEOSwift about unresolved identifiers for GEOSGeom_createPoint_r, etc.

I verified this is a problem starting with a new Xcode 10 project.

When I switch the C++ Standard Library to libstdcc++ it says "vector file not found" instead.

Not sure where to go from here. I've tried this on two difference machines.

Thanks

Using GEOSwift (3.0.1)
Using geos (3.7.0)

**Comment by JirkaApps** [comment] 2018-10-12 21:50
The `platform.h` file is now definitely not created during the install process via CocoaPods.
Using CocoaPods (1.5.3), GEOSwift (3.0.1), geos (3.7.0).

**Comment by macdrevx** [comment] 2018-10-16 17:42
Thanks for the bug report. I'll take a look ASAP.

**Comment by macdrevx** [comment] 2018-10-16 17:45
@joeuelk @JirkaApps can you please pass the `--verbose` flag to whichever pod command you're running (`install`/`update`) and share the output here?

**Comment by royalcheese71** [comment] 2018-10-22 08:38
```
-> Using GEOSwift (3.0.2)

-> Using Realm (3.11.1)
-> Using geos (3.7.0)
  - Running pre install hooks
   Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Adding development pod helper files to Pods project
  - Linking headers
  - Installing targets
    - Installing target `GEOSwift` iOS 8.0
      - Generating module map file at `Pods/Target Support Files/GEOSwift/GEOSwift.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/GEOSwift/GEOSwift-umbrella.h`
      - Generating Info.plist file at `Pods/Target Support Files/GEOSwift/Info.plist`
    - Installing target `Realm` iOS 8.0
      - Copying module map file to `Pods/Target Support Files/Realm/Realm.modulemap`
      - Generating Info.plist file at `Pods/Target Support Files/Realm/Info.plist`
 - Installing target `geos` iOS 8.0
      - Generating module map file at `Pods/Target Support Files/geos/geos.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/geos/geos-umbrella.h`
      - Generating Info.plist file at `Pods/Target Support Files/geos/Info.plist`
- Running post install hooks
    - Podfile
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`
Sending stats
      - GEOSwift, 3.0.2
      - Realm, 3.11.1
      - geos, 3.7.0
```

Same issue here

**Comment by royalcheese71** [comment] 2018-10-23 11:20
[aaaaagh.zip](https://github.com/GEOSwift/GEOSwift/files/2505402/aaaaagh.zip)

Here is a Swift test ,  a blank project just implementing geos 3.5. or geos 3.7 , and still the same issue than my Objective C project. 
No error running the pod install, the verbose doesn't seems to show a matter : 

the Derived Data are deleted, I've deleted Pod directory and xcode workspace. Also reinstalled xcode and suppressed preferences and settings, and compared build settings with another Xcode on another Mac.  Still not finding the solution yet.

we have two Mac which does'nt work and one which is building (?!) 

Doesn't seems to be a matter of version , compared also the version for pod, Mojave, xcode... 
But on the working one, there is several version of CocoaPods :
cocoapods (1.5.3, 1.3.1)
cocoapods-core (1.5.3, 1.4.0, 1.3.1)
cocoapods-deintegrate (1.0.2, 1.0.1)
cocoapods-downloader (1.2.1, 1.1.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.3.0)
cocoapods-try (1.1.0)

Other things seems to be on the same versions... 

We tried installing CocoaPod 1.3.1, but still doesn't work.
But the .h files are not all created during the pod install (platform.h, version.h)..

We tried your makefile  and it create the platform.h (and others.. ) the matter seems to come from your script prepare.sh ? 

I don't really know . Seems to be a matter between the creation of files and the packaging in Pod. 

Thanks a lot :)

**Comment by royalcheese71** [comment] 2018-10-23 12:28
Confirmed : It is a Pod problem, with the older version of Pod in project it's building. It does'nt work since last friday with a pod update which changed GEOSWIFT and geos

**Comment by macdrevx** [comment] 2018-10-23 13:42
Hi @royalcheese71 thanks for the extra info. I can see that there are header files missing in the sample project you shared. Those files are supposed to be generated by the `prepare.sh` script that runs when geos gets installed. Using cocoapods 1.6.0.beta.2, I ran `pod install` on your project, and it didn't fix the problem. Then I deleted the `Pods` directory and ran `pod install` again and the header files were generated.

I think we should collect some more info about your system to help narrow down what's going on. Can you please share the versions of autoconf autoheader, aclocal, automake, glibtool, and glibtoolize you have installed on the systems that aren't working?

Additionally, could you try cloning the geos podspec repo and running some of the prepare commands manually?

```
git clone https://github.com/GEOSwift/geos.git
git submodule update --init --recursive
cd geos
sh autogen.sh
./configure
./tools/svn_repo_revision.sh
```

Try running each of those lines individually and see if there are any errors reported. Feel free to share the results here and I can take a look too.

**Comment by macdrevx** [comment] 2018-10-23 23:27
Another thing I forgot to mention: unless your project has specific requirements to the contrary, you shouldn't need to modify the default C++ standard library setting anymore in Xcode 10.

**Comment by pwinde** [comment] 2018-10-25 09:06
@macdrevx We had the same issue and I ran the prepare commands as you suggested.

`./tools/svn_repo_revision.sh` failed with the following output:
```
Can't fetch local revision (neither .svn nor .git found)
#define GEOS_SVN_REVISION 0
Wrote rev '0' in file './geos_svn_revision.h'
```

**Comment by pwinde** [comment] 2018-10-25 09:10
Seems `svn_repo_revision.sh` is looking for the `.git` directory at the wrong location.
Changing line 11 to 
`elif test -d $top_srcdir"/../.git"; then` and running again produces the expected result(?):

```
#define GEOS_SVN_REVISION 4086
Wrote rev '4086' in file './geos_svn_revision.h'
```

**Comment by macdrevx** [comment] 2018-10-25 13:31
@pwinde Thanks for this. I've seen that too, though I've never seen it prevent `platform.h` (or any other file) from being generated. Is that what you were seeing?

I believe the same problem is happening with GEOS 3.7.0's `repo_revision.h`.

**Comment by macdrevx** [comment] 2018-10-25 13:39
Looks like we may need to be defining `top_srcdir` before invoking the script. That's how it's used in the GEOS makefile:

https://git.osgeo.org/gitea/geos/geos/src/tag/3.5.0/Makefile.am#L43

**Comment by pwinde** [comment] 2018-10-25 14:01
@macdrevx I did not test beyond the commands you listed so I did not get to a point where `platform.h` is generated.

**Comment by macdrevx** [comment] 2018-10-25 14:08
@pwinde `./configure` is the command that generates `platform.h`

**Comment by macdrevx** [comment] 2018-10-26 14:57
@joeuelk @JirkaApps @royalcheese71 Just wanted to check in with you all. I'd like to get to the bottom of this so that we can get this working for you (and anyone else who may be experiencing the same problems). Have you found any additional info that you can share?

**Comment by macdrevx** [comment] 2018-10-29 14:19
I'm not sure what `pod lib lint` is doing. I see the same error on my machine with that command. `pod spec lint`, on the other hand, works just fine and seems to have more relevance to what `pod install` does based on the configuration of the Xcode projects that they generate (test them both with ` --no-clean` and inspect the generated test projects).

**Comment by nylemusgrave** [comment] 2018-10-29 15:08
We have MS App center building out project with GEOSwift and it fails for all build attempts.

2018-10-24T16:20:15.1965310Z /Users/vsts/agent/2.140.2/work/1/s/LandDB_iOS_Mobile/Pods/geos/geos/include/geos/geom/Coordinate.h:19:10: fatal error: 'geos/platform.h' file not found

Local builds from xcode work fine for me, not sure what process differences are causing this to fail.

**Comment by joeuelk** [comment] 2018-10-29 16:12
FYI, in order to get the latest build to work I installed with cocopods and executed the following:

`git clone https://github.com/GEOSwift/geos.git
cd geos
git checkout 3.5.0
git submodule update --init --recursive
cd geos
sh autogen.sh
./configure
./tools/svn_repo_revision.sh`

And then ran the coco pods update again. I didn't have to make any other changes in Xcode.

**Comment by macdrevx** [comment] 2018-10-29 17:37
I wonder whether we may be running into a caching issue with the `prepare_command`: https://github.com/CocoaPods/CocoaPods/issues/7192. The caches on my machine are at `~/Library/Caches/CocoaPods/Pods/Release/geos`. Can someone check what's showing up there on a machine where this isn't working?

**Comment by macdrevx** [comment] 2018-10-29 17:41
Using cocoapods 1.6.0.beta.2, if I delete the `~/Library/Caches/CocoaPods/Pods/Release/geos` directory and my project's `Pods` directory and then run `pod install --verbose`, I can see the output of `prepare.sh`.

**Comment by macdrevx** [comment] 2018-10-29 17:46
I'm particularly interested whether the file `~/Library/Caches/CocoaPods/Pods/Release/geos/3.7.0-de7d1/geos/include/geos/platform.h` exists. (I'm not sure whether the 3.7.0-de7d1 directory will be named exactly that for everyone. It will certainly be named something else if you're on 3.5.0)

**Comment by nylemusgrave** [comment] 2018-10-29 18:41
For me its only happening on MS App Centers build process, of which gets completely rebuilt every-time, so I wouldn't think cache would be an issue here. Locally it works fine for me with all the same configuration..I haven't been able to find the difference. Locally I saw those files correct in my cache directory you stated above, I deleted the cache folders and everything still builds for me locally.

**Comment by macdrevx** [comment] 2018-10-30 14:14
Here's a nice way to manage the CocoaPods cache.

See what CocoaPods has cached about geos:
```
$ pod cache list geos
```

Remove all caches for geos:
```
$ pod cache clean geos --all
```

@nylemusgrave could you try running `pod cache list geos` before your `pod install` step in your App Center build just to make sure?

**Comment by nylemusgrave** [comment] 2018-10-31 18:57
@macdrevx This worked for me! Clearing the cache inside of the MS App Center process fix the issue for me.

**Comment by KarenK1995** [comment] 2018-10-31 19:03
What is MS App Center, I am using xcode

**Comment by KarenK1995** [comment] 2018-10-31 19:49
@macdrevx Thank you for your response but I fixed this other way. I removing everything from Podfile run pod install than after that put back everything and again pod install.

**Comment by macoapps** [comment] 2019-01-02 13:56
@macdrevx I tried everything listed above, but no way. 'platform.h' is still missing in geos, and I can't build GEOSwift either. Too bad, because this is really the best lib ever for GeoJSON !
My conf is macOS 10.14.2 (18C54) and XCode 10.1 (10B61).

**Comment by shanminxu** [comment] 2019-01-04 19:43
This works for me:
brew install autoconf automake libtool
pod install

**Comment by macoapps** [comment] 2019-01-04 20:18
> This works for me:
> brew install autoconf automake libtool
> pod install

Man, you saved my life !

**Comment by macdrevx** [comment] 2019-01-04 22:03
Thanks @shanminxu, and glad this fixed the issue for you @macoapps. I’m going to close this thread now since it seems to be a little long and relate to multiple issues at this point.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by macdrevx** 2019-01-04 22:03 UTC

**Comment by nylemusgrave** [comment] 2019-01-09 19:53
This issue just started happening for me again out of the blue after working for a long time. 

brew install autoconf automake libtool

pod cache list geos
pod cache clean geos --all

pod install

I run the commands above every build, was working but now I'm getting the error when archiving even tho there is no cache found to clear.
