### ISSUE TITLE
SPM-generated Xcode project does not build

### ISSUE THREAD

**Issue by eandrade21** [GEOSwift/GEOSwift#194] opened 2020-02-13 20:22 UTC
**Environment**

Swift Version: 5.1.3
Target: x86_64-apple-darwin19.3.0
MacOS: macOS Catalina 10.15.3

**Steps to Reproduce**

mkdir GeoZone
cd GeoZone
swift package init --type executable --name GeoZone
Update Swift.package as below
swift package update
swift package generate-xcodeproj
open GeoZone.xcodeproj
Build the executable - Cmd +B <-- ISSUE HERE

**Compile Error:**

/Users/eandrade/GeoZone/.build/checkouts/geos/Sources/geos/src/algorithm/BoundaryNodeRule.cpp:19:10: fatal error: 'geos/algorithm/BoundaryNodeRule.h' file not found
#include <geos/algorithm/BoundaryNodeRule.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/eandrade/GeoZone/.build/checkouts/geos/Sources/geos/src/algorithm/BoundaryNodeRule.cpp:19:10: note: did not find header 'algorithm/BoundaryNodeRule.h' in framework 'geos' (loaded from '/Users/eandrade/Library/Developer/Xcode/DerivedData/GeoZone-azxhtiysgxdwzydubcqmwjlbpgvj/Build/Products/Debug')
1 error generated.

**Package.swift**
```

// swift-tools-version:5.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "GeoZone",
    products: [
    .executable(name: "GeoZone", targets: ["GeoZone"]),
    ], 
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/GEOSwift/GEOSwift.git", from: "6.0.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "GeoZone",
            dependencies: [
"GEOSwift"
]),
        .testTarget(
            name: "GeoZoneTests",
            dependencies: ["GeoZone"]),
    ]
)

```
**Package.resolved**
```
{
  "object": {
    "pins": [
      {
        "package": "geos",
        "repositoryURL": "https://github.com/GEOSwift/geos.git",
        "state": {
          "branch": null,
          "revision": "4285f0903eacafd98705f047519c16e9dd09aba2",
          "version": "4.1.0"
        }
      },
      {
        "package": "GEOSwift",
        "repositoryURL": "https://github.com/GEOSwift/GEOSwift.git",
        "state": {
          "branch": null,
          "revision": "dfc9da755f8966dae4b97073d7c2301065cbbbc1",
          "version": "6.0.0"
        }
      }
    ]
  },
  "version": 1
}
```

**Comment by macdrevx** [comment] 2020-02-16 13:50
Thanks @ueandrade. I'm able to reproduce this following the steps you provided. Not sure of the cause yet.

**Comment by macdrevx** [comment] 2020-02-16 14:55
The problem is that the geos target in the generated Xcode project has the Header Search Path `include` instead of `$(SRCROOT)/.build/checkouts/geos/Sources/geos/include`

<img width="1326" alt="Screen Shot 2020-02-16 at 9 49 48 AM" src="https://user-images.githubusercontent.com/205658/74606892-2c841880-50a2-11ea-946e-b7604e100281.png">

You'll have to change that setting after running `swift package generate-xcodeproj`. I'll keep investigating to see whether this is a bug in the generator, whether we're using Package.swift incorrectly in GEOSwift, or whether it's some other issue I'm not seeing right now.

**Comment by macdrevx** [comment] 2020-02-16 15:15
https://bugs.swift.org/browse/SR-12215

**Comment by macdrevx** [comment] 2020-03-05 03:36
I updated the title to try to help other folks find this if they're having similar issues.

**Comment by macdrevx** [comment] 2021-08-22 20:43
The Swift team has decided not to fix the underlying issue because `generate-xcodeproj` is being deprecated. As such, I'm going to close this issue.

**Closed by macdrevx** 2021-08-22 20:43 UTC
Labels: blocked, has workaround
