### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by valentary** [GEOSwift/GEOSwift#239] opened 2022-01-15 15:46 UTC
I'm trying to include this as a package in an iOS project (Or rather this PR : https://github.com/GEOSwift/GEOSwift/pull/228)

But it won't build , I get errors like :
`
▸ Linking geos.o
▸ Processing empty-geos.plist
▸ Linking geos
❌  Undefined symbols for architecture x86_64
> Symbol: ___llvm_profile_runtime
> Referenced from: ___llvm_profile_runtime_user in geos.o
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by macdrevx** [comment] 2022-01-16 02:30
Have you tried explicitly including geos as a dependency too? https://github.com/GEOSwift/GEOSwift#swift-package-manager

Can you reproduce in a sample project that you could attach here?

What version of Xcode are you using?

**Comment by valentary** [comment] 2022-01-17 09:52
I'll see if I can try these things over this week

XCode version is currently 13.1 I'm updating to the latest version now but it takes several hours....

For the GEOSwift version, I'm pulling from directly from the branch in the PR

**Comment by valentary** [comment] 2022-01-18 09:35
I tried adding the geos package as a seperate dependency, it required an older version to be compatible with GEOSwift fro the packages to resolve, I used 6.0.1 -> To next major version
Unfortunately it did not solve the problem

**Comment by romnes** [comment] 2022-01-21 17:31
Attached is a sample project reproducing this issue. It started out as a vanilla iOS app using the "App" template in Xcode. I then converted the tests to use a test plan and in the `GeoSwiftSample.xctestplan` file I turned on `Code Coverage`. This triggers the issue.

Turning *off*  "Code Coverage" in the test plan is a work-around for this issue.

<img width="634" alt="Screenshot 2022-01-21 at 18 30 15" src="https://user-images.githubusercontent.com/181965/150572986-a8ecac6f-4c67-40f9-9423-49a9b0954f2e.png">

[GeoSwiftSample.zip](https://github.com/GEOSwift/GEOSwift/files/7915556/GeoSwiftSample.zip)

**Comment by macdrevx** [comment] 2022-01-21 18:32
Okay, sounds like a duplicate of https://github.com/GEOSwift/geos/issues/14. Sorry for not identifying that more quickly. We unfortunately don't know how to solve this at the moment.

**Comment by valentary** [comment] 2022-01-21 21:01
Thanks for Reproducing the error! We indeed use code coverage, and turning
it off for a single package is not really an option for us.

Strange that it should cause such an error though
-- 

*George Brown* | Senior Developer
Pix4D, Route de Renens 24, 1008 Prilly, Switzerland
***@***.***
*www.pix4d.com <https://www.pix4d.com/>*
* <https://www.facebook.com/Pix4D/>  <https://twitter.com/pix4d>
<https://www.youtube.com/channel/UCXHBqjCbv1wj_-itfvpVNIA?sub_confirmation=1>
<https://www.instagram.com/pix4d_official>
<https://www.linkedin.com/company/pix4d>*

**Comment by macdrevx** [comment] 2023-02-15 23:58
Closing as a duplicate. Please add new info to https://github.com/GEOSwift/geos/issues/14 if you have any.

**Closed by macdrevx** 2023-02-15 23:58 UTC
