### ISSUE TITLE
Non WGS84 spatial reference system

### ISSUE THREAD

**Issue by madhavajay** [GEOSwift/GEOSwift#151] opened 2019-04-11 03:28 UTC
Im trying to recreate some code I wrote for shapely in python which also uses GEOS.
All I want to do is to construct some shapes like trapezoids and squares and find their intersections and area etc.

It seems that when I try to do this with GEOSwift it only allows the points to be in Latitude / Longitude?

The way I managed to draw a trapezoid and avoid errors was to reduce the scale of my numbers by dividing them down and making them negative.

I figured out that must be because of the directionality and scale of valid Lat Lon coordinates.
Is there any way to simply disable that and just do plain Geometry in an unlimited flat cartesian space?

Here is my code that doesn't work:
```

let bl = Coordinate(x: Double(73), y: Double(510))
let br = Coordinate(x: Double(373), y: Double(510))
let tr = Coordinate(x: Double(243), y: Double(340))
let tl = Coordinate(x: Double(203), y: Double(340))
let linearRing = LinearRing(points: [
    tl,
    tr,
    br,
    bl,
    tl
])
let polygon = Polygon(shell: linearRing!, holes: [])
```

When I scale it down its still the wrong direction:
https://imgur.com/a/wqqWcFB

When I add minus signs to the values its not working, but I don't want to have to do this for everything and then convert it back:
https://imgur.com/a/QcixVBF

**Comment by macdrevx** [comment] 2019-04-22 01:12
Hi @madhavajay. Can you please provide steps to reproduce the problem including expected & actual results? I ran the code snippet you shared and didn't see any crashes, so I'm guessing the problem is something else.

In its current state, GEOSwift is kind of a mashup of GeoJSON and GEOS. The GeoJSON spec is specifically about representing geographic shapes. GEOS is more general, but the two have many concepts that they share in common.

I agree that it would be useful if GEOSwift allowed for doing "plain geometry". I'm experimenting with a fairly major redesign of this library (still early stages), and initially I've been focusing on better support for GeoJSON, but this feedback has made me realize that supporting plain geometry may be another key element. In the redesign, I think it'd basically amount to renaming the fields of a Point to x and y.

**Comment by madhavajay** [comment] 2019-04-24 03:30
@macdrevx regarding the future of the library, yes i think it's a hugely useful library for doing complex geometric calculations in a few lines, which is why i found shapely in python and then this library for swift in the first place.

I still get this error when i run that code in a playground:
https://imgur.com/a/GFrtNRf

As you can see if i divide all the values by 100 it works fine:
https://imgur.com/a/rjz4wZA

Unfortunately its not easy to see the issue since its a SIGABRT.

If you say it works, maybe thats the code but not the playground QuickLook. Maybe it's not able to find the locations on the map due to the coords being too high on the Lat Lon scale?

Also do you know if there are any kind of magic round earth projection changes to the math for things like area etc that are incorporated. I would assume that would be necessary, since the earth is indeed not flat contrary to recent popular ideas 🤣, however users with arbitrary number scales in flat co-ordinate space wouldn't want these affecting their calculations surely?

**Comment by macdrevx** [comment] 2019-04-25 02:31
I was only able to reproduce this error in the playground and not if I ran the same code in a sample project. I noticed the following message in the log:

`libc++abi.dylib: terminating with uncaught exception of type NSException`

That gave me the idea to try to catch that `NSException`. First, I tried using https://github.com/eggheadgames/SwiftTryCatch, but for some reason I was getting the same error. Then I found this [article](https://www.swiftbysundell.com/posts/swift-playgrounds-tips-tricks) on Swift By Sundell that shows how to use `NSSetUncaughtExceptionHandler`. That was just what I needed.

I added the following to the beginning of the playground:

```
NSSetUncaughtExceptionHandler { exception in
    print("Exception name: \(exception.name.rawValue)")
    print("Exception reason: \(String(describing: exception.reason))")
    print("Exception userInfo: \(String(describing: exception.userInfo))")
    print("\(exception.callStackSymbols.joined(separator: "\n"))")
}
```

which yielded:

```
Exception name: NSInvalidArgumentException
Exception reason: Optional("Invalid Region <center:+425.00000000, +223.00000000 span:+170.00000000, +300.00000000>")
Exception userInfo: nil
0   CoreFoundation                      0x0000000106ea26fb __exceptionPreprocess + 331
1   libobjc.A.dylib                     0x000000010644eac5 objc_exception_throw + 48
2   CoreFoundation                      0x0000000106ea2269 -[NSException raise] + 9
3   MapKit                              0x000000011e02a509 -[MKMapView setRegion:animated:] + 665
4   MapKit                              0x000000011e02a591 -[MKMapView setRegion:] + 75
5   GEOSwift                            0x000000011dd4dfb7 $s8GEOSwift8GeometryC20debugQuickLookObjectyXlSgyF + 1527
6   GEOSwift                            0x000000011dd4ed24 $s8GEOSwift8GeometryC20debugQuickLookObjectyXlSgyFTo + 36
7   PlaygroundLogger                    0x000000011b4dda78 globalinit_33_86996C1BC443F28F24E6A34F24210E4B_func8 + 2776
8   PlaygroundLogger                    0x000000011b4d8a40 globalinit_33_B1F54B50FE3698781248948D54A93147_func6 + 496
9   PlaygroundLogger                    0x000000011b4da7c4 playground_log_hidden + 292
10  ???                                 0x00000001214e055d 0x0 + 4853728605
11  GEOSwift                            0x0000000104e65620 main + 0
12  CoreFoundation                      0x0000000106e09aec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
13  CoreFoundation                      0x0000000106e092b0 __CFRunLoopDoBlocks + 336
14  CoreFoundation                      0x0000000106e03b34 __CFRunLoopRun + 1252
15  CoreFoundation                      0x0000000106e03302 CFRunLoopRunSpecific + 626
16  GraphicsServices                    0x000000010ebc02fe GSEventRunModal + 65
17  UIKitCore                           0x000000010afaeba2 UIApplicationMain + 140
18  GEOSwift                            0x0000000104e656ed main + 205
19  libdyld.dylib                       0x0000000108754541 start + 1
libc++abi.dylib: terminating with uncaught exception of type NSException
```

It turns out that the playground is calling into quicklook and GEOSwift's quicklook support is all based on MapKit, which has some requirements around coordinates being within a certain range.

Apart from this quicklook & mapkit stuff, I don't think GEOSwift imposes any additional restrictions on doing arbitrary geometry like you want to.

Again, this gets at a fundamental question about the purpose of this library. Having the quicklook support *with* map kit is nice for people working on geographic apps. Do we want GEOSwift to be the "Swift Geographic Engine" as it's branded now, or is there interest in generalizing it to be the "Swift Geometry Engine"?

I'm definitely open to the latter, and I think we could still include robust support for GeoJSON. Perhaps we could split the MapKit & quicklook support out into a separate library specifically for people who want it. That would also open up the possibility of having alternative approaches to quicklook, which could be valuable for people who aren't concerned with maps. Additionally, it would increase the portability of the core lib since MapKit isn't available on all platforms.

**Comment by madhavajay** [comment] 2019-04-25 05:06
Awesome to see how to properly debug an issue like this! I think even just having the constructor allow for lat, lon vs x, y or some other flag would be sufficient in letting people opt out of the MapKit restrictions.

If the Map based constructors validated the coords they could reject creation based on invalid lat lon values. This would also help catch issues. For now ill keep my coords at 100th of the size but if the rebuild includes this functionality that would be great! :)

I really love the QuickLook functionality so it would still be awesome to see a shape rendering, but the map would be unnecessary in normal planar geometry. Maybe it could even have a light x, y grid behind it. We can already see that Swift will be coming to Jupyter Notebooks soon. In addition it's likely to make its way to other platforms like Windows and Android. Eventually the iPad Playgrounds might also support external Frameworks. So if you want to rebuild anyway it makes sense to allow all the great functionality of geos to shine through to all these potential future platforms and use cases.

Speaking of QuickLook I noticed it doesn't work for me during Debugging with break points. It would be super cool if it did, since a picture tells a 1000 words when you're debugging a shape or its intersection with other shapes. 👍

**Comment by macdrevx** [comment] 2019-04-26 01:12
@madhavajay I'm going to close this issue for now, but we will keep these points in mind as we work on the next major update.

**Closed by macdrevx** 2019-04-26 01:12 UTC
Labels: question

**Comment by madhavajay** [comment] 2019-04-26 05:31
Ok no worries! 👍
