### ISSUE TITLE
Build errors in Xcode

### ISSUE THREAD

**Issue by rausnitz** [GEOSwift/GEOSwift#188] opened 2019-11-13 18:51 UTC
<img width="371" alt="Screen Shot 2019-11-13 at 10 45 05 AM" src="https://user-images.githubusercontent.com/6132143/68793917-c4391d00-0602-11ea-8ff9-4d1295c5823b.png">

Here's my Package.resolved:
```
        "package": "geos",
        "repositoryURL": "https://github.com/GEOSwift/geos.git",
        "state": {
          "branch": null,
          "revision": "4285f0903eacafd98705f047519c16e9dd09aba2",
          "version": "4.1.0"
        }
      },
      {
        "package": "GEOSwift",
        "repositoryURL": "https://github.com/GEOSwift/GEOSwift.git",
        "state": {
          "branch": null,
          "revision": "dfc9da755f8966dae4b97073d7c2301065cbbbc1",
          "version": "6.0.0"
        }
      },
```

I'm getting the above errors only in Xcode. When I build from the command line, building succeeds.

It's possible that this issue is particular to Vapor. I'm cleaning, updating, building, and generating the Xcode project using the Vapor toolbox (`vapor clean`, `vapor update`, `vapor build`, `vapor xcode`).

Xcode 11.1, Swift 5.1.

**Comment by macdrevx** [comment] 2019-11-14 00:07
Hi @rausnitz, can you attach a sample project the reproduces this behavior?

**Comment by ueandrade** [comment] 2020-02-16 02:56
@rausnitz were you able to solve this issue?

**Comment by macdrevx** [comment] 2020-02-16 15:15
I bet this is the same as #194

**Comment by macdrevx** [comment] 2020-03-05 03:34
@rausnitz @ueandrade I'm going to close this because I believe it's the same as #194. If you disagree, please feel free to reopen it with more info.

There's some discussion in #194 about the root cause, which is an issue with SPM. There's a workaround described there that might help you until it's fixed.

**Closed by macdrevx** 2020-03-05 03:34 UTC
