### ISSUE TITLE
SVN down? pod install Error installing geos

### ISSUE THREAD

**Issue by jwilson85** [GEOSwift/GEOSwift#80] opened 2018-03-05 18:16 UTC
```bash
Analyzing dependencies
Downloading dependencies
Using Alamofire (4.6.0)
Using Bolts (1.9.0)
Using FBAnnotationClusteringSwift (2.0)
Using FBSDKCoreKit (4.29.0)
Using FBSDKLoginKit (4.29.0)
Using FacebookCore (0.3.0)
Using FacebookLogin (0.3.0)
Using Firebase (3.17.0)
Using FirebaseAnalytics (3.9.0)
Using FirebaseAuth (3.1.1)
Using FirebaseCore (3.6.0)
Using FirebaseInstanceID (1.0.10)
Using FirebaseMessaging (1.2.3)
Installing GEOSwift (2.1.3)
Using GTMOAuth2 (1.1.6)
Using GTMSessionFetcher (1.1.12)
Using Google (3.1.0)
Using GoogleAnalytics (3.17.0)
Using GoogleMaps (2.5.0)
Using GooglePlacePicker (2.5.0)
Using GooglePlaces (2.5.0)
Using GoogleSignIn (4.1.1)
Using GoogleToolboxForMac (2.1.3)
Using Protobuf (3.5.0)
Using SDWebImage (3.8.2)
Using SWXMLHash (4.2.5)
Using SwiftWebViewProgress (0.3)
Using SwiftyJSON (3.0.0)
Installing geos (3.5.0)

[!] Error installing geos
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force https://svn.osgeo.org/geos/tags/3.5.0 /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3

A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/tests
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/capi
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/examples
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/cmake
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/cmake/modules
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/TODO
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/.gitignore
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/tests/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/tests/TESTING.txt
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/tests/runtests.py
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/tests/test_geometry.py
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/tests/example.py
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_operations.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_version.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/capi/geos_c.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/capi/geos_ts_c.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/capi/CMakeLists.txt
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/cmake/modules/GenerateSourceGroups.cmake
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/geos.py
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/geos.pth
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos-dev.dirs
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/watch
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/capi/geos_c.h.in
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/makedoc
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/copyright
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/cmake/modules/CheckPrototypeExists.cmake
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/geos-config.1
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos-dev.install
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/test
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos-doc.docs
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/changelog
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/Makefile
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/compat
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/README.Debian
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos.dirs
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/rules
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/acsite.m4
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/intervalrtree
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos.install
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/AUTHORS
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos-dev.manpages
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/geos_wrap.cxx
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/python.i
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/python/README.txt
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/README
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/geos_wrap.cxx
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/ruby.i
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_geometry.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/test/test.php
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/geos.c
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/TODO
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/test/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/intervalrtree/IntervalRTreeNode.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree/Key.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/intervalrtree/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/intervalrtree/IntervalRTreeLeafNode.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/intervalrtree/SortedPackedIntervalRTree.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/example.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_envelope.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_coordinate_sequence.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_helper.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/geos_tests.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_relations.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_srid.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_combinations.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_io.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/ruby/test/test_buffer.rb
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/swig/geos.i.in
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/capi/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/cmake/cmake_uninstall.cmake.in
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/cmake/modules/COPYING-CMAKE-SCRIPTS
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos-doc.doc-base
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos.docs
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/control
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/debian/libgeos-dev.docs
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/makefile.vc
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/php_geos.h
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/php/test/crashme.php
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/intervalrtree/IntervalRTreeBranchNode.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree/Bintree.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree/Root.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/sweepline
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/chain
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/linearref
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree/Node.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree/AbstractNode.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree/Interval.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree/STRtree.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree/SIRtree.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/Key.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree/Makefile.am
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree/AbstractSTRtree.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/Node.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/bintree/NodeBase.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree/Interval.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/strtree/ItemBoundable.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/Root.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/Quadtree.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/geomgraph
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/geomgraph/index
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/NodeBase.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/sweepline/SweepLineIndex.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/chain/MonotoneChainSelectAction.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/StringTokenizer.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/CLocalizer.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/IntervalSize.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/sweepline/SweepLineInterval.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/chain/MonotoneChainOverlapAction.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/WKBWriter.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/WKBReader.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/ParseException.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/linearref/LocationIndexOfLine.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/linearref/ExtractLineByLocation.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/ByteOrderDataInStream.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/quadtree/DoubleBits.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/sweepline/SweepLineEvent.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/index/chain/MonotoneChainBuilder.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/ByteOrderValues.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/WKTWriter.cpp
A    /var/folders/bp/pfl4h2vs0jb_n8w1qkxx_t780000gn/T/d20180305-24807-zovpk3/src/io/WKTReader.cpp
svn: E175013: Access to '/geos/!svn/rvr/4086/tags/3.5.0/src/linearref/LinearGeometryBuilder.cpp' forbidden
svn: E200042: Additional errors:
svn: E175013: Access to '/geos/!svn/rvr/4086/tags/3.5.0/src/linearref/LinearIterator.cpp' forbidden
```

**Comment by jwilson85** [comment] 2018-03-05 18:43
I tried the below pod install.
`
pod 'GEOSwift', :git => 'https://github.com/mojtabacazi/GEOSwift.git', :branch => 'develop'
`
However, the install just hangs for 20 min. In his example he includes: 
`
source 'https://github.com/mojtabacazi/Specs.git'
`
For me that causes other pods to fail. saying they cant find the repo



Is there an alternative to the GEO library? it looks as if this project has been abandoned.

**Comment by vfn** [comment] 2018-03-05 22:52
Duplicate of https://github.com/GEOSwift/GEOSwift/issues/78

**Closed by vfn** 2018-03-05 22:52 UTC
